-- V10: Hospitalisation & gestion des lits (module 10). Rooms (which hold one or more beds via
-- `capacity`) and the patient stays in them. Bed occupancy is NOT stored — it is derived at read
-- time from the count of hospitalizations in status ADMIS for a room, so a transfer/discharge
-- frees a bed simply by flipping the stay's status.
--   * rooms            — reference of rooms/beds (number, department, type, capacity, daily rate)
--   * hospitalizations — a patient's stay (admission → sortie/transfert/décès)
--
-- DDL kept compatible with BOTH PostgreSQL (prod) and H2 (dev), matching prior migrations.

-- ── rooms ─────────────────────────────────────────────────────────────────────
CREATE TABLE rooms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number   VARCHAR(20)  NOT NULL UNIQUE,
    department_id BIGINT REFERENCES departments (id),
    type          VARCHAR(20)  NOT NULL DEFAULT 'STANDARD', -- STANDARD, PRIVE, SOINS_INTENSIFS, MATERNITE
    capacity      INT          NOT NULL DEFAULT 1,
    daily_rate    NUMERIC(12,2) NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    notes         TEXT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rooms_department ON rooms (department_id);
CREATE INDEX idx_rooms_is_active  ON rooms (is_active);

INSERT INTO rooms (room_number, department_id, type, capacity, daily_rate) VALUES
    ('101', (SELECT id FROM departments WHERE code = 'MED_GEN'),   'STANDARD',        2, 15000.00),
    ('102', (SELECT id FROM departments WHERE code = 'MED_GEN'),   'STANDARD',        2, 15000.00),
    ('103', (SELECT id FROM departments WHERE code = 'MED_GEN'),   'PRIVE',           1, 35000.00),
    ('201', (SELECT id FROM departments WHERE code = 'PEDIATRIE'), 'STANDARD',        3, 12000.00),
    ('202', (SELECT id FROM departments WHERE code = 'PEDIATRIE'), 'PRIVE',           1, 30000.00),
    ('301', (SELECT id FROM departments WHERE code = 'MATERNITE'), 'MATERNITE',       2, 20000.00),
    ('302', (SELECT id FROM departments WHERE code = 'MATERNITE'), 'PRIVE',           1, 40000.00),
    ('USI1',(SELECT id FROM departments WHERE code = 'URGENCES'),  'SOINS_INTENSIFS', 1, 75000.00);

-- ── hospitalizations ──────────────────────────────────────────────────────────────
CREATE TABLE hospitalizations (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id             BIGINT NOT NULL REFERENCES patients (id),
    room_id                BIGINT NOT NULL REFERENCES rooms (id),
    doctor_id              BIGINT NOT NULL REFERENCES users (id),
    admission_date         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    discharge_date         TIMESTAMP,
    admission_reason       TEXT NOT NULL,
    diagnosis_on_discharge TEXT,
    status                 VARCHAR(20) NOT NULL DEFAULT 'ADMIS', -- ADMIS, TRANSFERE, SORTI, DECEDE
    notes                  TEXT,
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP
);

CREATE INDEX idx_hosp_patient ON hospitalizations (patient_id);
CREATE INDEX idx_hosp_room    ON hospitalizations (room_id);
CREATE INDEX idx_hosp_status  ON hospitalizations (status);
