-- V11: Maternité & Obstétrique (module 11). A long-lived pregnancy dossier (carnet de grossesse),
-- one per patiente, plus its antenatal consultations (CPN). Unlike lab/radiology the parent is not a
-- single encounter: it spans the whole pregnancy and is closed out by an accouchement.
--   * maternity_records — the dossier (gravidité/parité, DDR/DPA, accouchement + nouveau-né), one
--                         per patiente (patient_id UNIQUE). Status EN_COURS → ACCOUCHEE → CLOTURE.
--   * prenatal_visits   — the CPN visits (poids, tension, hauteur utérine, RCF, vaccins…).
--
-- DDL kept compatible with BOTH PostgreSQL (prod) and H2 (dev), matching prior migrations.

-- ── maternity_records ────────────────────────────────────────────────────────────
CREATE TABLE maternity_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id        BIGINT NOT NULL UNIQUE REFERENCES patients (id),
    doctor_id         BIGINT REFERENCES users (id),
    gravidity         INT,
    parity            INT,
    last_period_date  DATE,
    expected_due_date DATE,
    delivery_date     DATE,
    delivery_type     VARCHAR(20),  -- NATUREL, CESARIENNE, FORCEPS
    delivery_outcome  VARCHAR(20),  -- VIVANT, MORT_NE, AVORTEMENT
    newborn_weight_g  INT,
    newborn_apgar1    INT,
    newborn_apgar5    INT,
    newborn_gender    VARCHAR(10),
    complications     TEXT,
    notes             TEXT,
    status            VARCHAR(20) NOT NULL DEFAULT 'EN_COURS', -- EN_COURS, ACCOUCHEE, CLOTURE
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP
);

CREATE INDEX idx_maternity_patient ON maternity_records (patient_id);
CREATE INDEX idx_maternity_status  ON maternity_records (status);

-- ── prenatal_visits ───────────────────────────────────────────────────────────────
CREATE TABLE prenatal_visits (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maternity_record_id   BIGINT NOT NULL REFERENCES maternity_records (id),
    doctor_id             BIGINT NOT NULL REFERENCES users (id),
    visit_date            DATE NOT NULL,
    visit_number          INT NOT NULL,
    gestational_age_weeks INT,
    weight_kg             NUMERIC(5,2),
    bp_systolic           INT,
    bp_diastolic          INT,
    fetal_heart_rate      INT,
    uterine_height_cm     NUMERIC(4,1),
    presentation          VARCHAR(30),  -- CEPHALIQUE, SIEGE, TRANSVERSE…
    edema                 BOOLEAN,
    proteinuria           BOOLEAN,
    iron_supplemented     BOOLEAN,
    ttv_vaccine           BOOLEAN,
    observations          TEXT,
    recommendations       TEXT,
    next_visit_date       DATE,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_prenatal_record ON prenatal_visits (maternity_record_id);
