-- V12: Facturation & Paiements (module 12 / spec 07). The aggregation module — invoices pull
-- billable lines (from consultations/hospitalizations or entered manually), apply the insurance
-- coverage %, and track encaissement via payments. act_catalog + insurance_providers already
-- exist (V4). DDL kept compatible with BOTH PostgreSQL (prod) and H2 (dev), matching prior waves.

-- ── invoices ─────────────────────────────────────────────────────────────────
CREATE TABLE invoices (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number             VARCHAR(25)  NOT NULL UNIQUE,          -- FAC-2026-00001
    patient_id                 BIGINT       NOT NULL REFERENCES patients (id),
    consultation_id            BIGINT       REFERENCES consultations (id),
    hospitalization_id         BIGINT       REFERENCES hospitalizations (id),
    insurance_id               BIGINT       REFERENCES insurance_providers (id),
    insurance_coverage_percent NUMERIC(5,2) DEFAULT 0,
    subtotal                   NUMERIC(12,2) NOT NULL DEFAULT 0,
    insurance_amount           NUMERIC(12,2) NOT NULL DEFAULT 0,
    patient_amount             NUMERIC(12,2) NOT NULL DEFAULT 0,      -- à payer par le patient
    paid_amount                NUMERIC(12,2) NOT NULL DEFAULT 0,
    status                     VARCHAR(20)  NOT NULL DEFAULT 'EN_ATTENTE', -- EN_ATTENTE, PARTIEL, PAYE, ANNULE
    due_date                   DATE,
    notes                      TEXT,
    created_by                 BIGINT       REFERENCES users (id),
    created_at                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP
);

CREATE INDEX idx_invoices_patient ON invoices (patient_id);
CREATE INDEX idx_invoices_status  ON invoices (status);

-- ── invoice_items ────────────────────────────────────────────────────────────
CREATE TABLE invoice_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT       NOT NULL REFERENCES invoices (id) ON DELETE CASCADE,
    act_id      BIGINT       REFERENCES act_catalog (id),
    description VARCHAR(255) NOT NULL,
    quantity    INT          NOT NULL DEFAULT 1,
    unit_price  NUMERIC(12,2) NOT NULL,
    total_price NUMERIC(12,2) NOT NULL
);

CREATE INDEX idx_invoice_items_invoice ON invoice_items (invoice_id);

-- ── payments ─────────────────────────────────────────────────────────────────
CREATE TABLE payments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT       NOT NULL REFERENCES invoices (id),
    amount      NUMERIC(12,2) NOT NULL,
    method      VARCHAR(30)  NOT NULL,   -- ESPECES, CARTE, ORANGE_MONEY, MTN_MOMO, WAVE, VIREMENT, ASSURANCE
    reference   VARCHAR(100),            -- numéro de transaction mobile money
    paid_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cashier_id  BIGINT       REFERENCES users (id),
    notes       TEXT
);

CREATE INDEX idx_payments_invoice ON payments (invoice_id);
CREATE INDEX idx_payments_paid_at ON payments (paid_at);
