-- V13: Notifications (module 13 / spec 12). A single outbound queue feeding three channels
-- (SMS / EMAIL / IN_APP). Upstream modules call NotificationService to enqueue a row
-- (status EN_ATTENTE); a @Scheduled drain dispatches it (→ ENVOYE / ECHEC). In dev there are
-- no provider keys, so a logging sender marks rows ENVOYE; IN_APP rows are read back by the
-- in-app inbox + nav badge. DDL kept compatible with BOTH PostgreSQL (prod) and H2 (dev).

CREATE TABLE notifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       REFERENCES users (id),     -- destinataire interne (null = patient)
    patient_id    BIGINT       REFERENCES patients (id),  -- patient concerné (le cas échéant)
    type          VARCHAR(30)  NOT NULL,                  -- RAPPEL_RDV, RESULTAT_LABO, STOCK_ALERTE, FACTURE_IMPAYEE, SYSTEM
    channel       VARCHAR(10)  NOT NULL,                  -- SMS, EMAIL, IN_APP
    recipient     VARCHAR(150) NOT NULL,                  -- téléphone, email, ou nom d'utilisateur
    subject       VARCHAR(255),
    body          TEXT         NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'EN_ATTENTE', -- EN_ATTENTE, ENVOYE, ECHEC
    read_at       TIMESTAMP,                              -- lecture in-app (null = non lu)
    scheduled_at  TIMESTAMP,                              -- null = à envoyer immédiatement
    sent_at       TIMESTAMP,
    error_message TEXT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notif_status    ON notifications (status, scheduled_at);
CREATE INDEX idx_notif_user      ON notifications (user_id, read_at);
CREATE INDEX idx_notif_patient   ON notifications (patient_id);
