-- V14: Journal d'audit (P1.2). Trace immuable « qui / quoi / quand » sur les actions
-- métier sensibles (création/modif patient, validation labo, encaissement, etc.).
-- Alimenté par AuditAspect (@AfterReturning sur les méthodes service annotées @Audited),
-- jamais par l'utilisateur. Append-only : aucune mise à jour ni suppression applicative.
-- DDL compatible PostgreSQL (prod) ET H2 (dev).

CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,                                  -- auteur (null si système / non authentifié)
    username    VARCHAR(150) NOT NULL DEFAULT 'system',  -- nom d'utilisateur au moment de l'action
    action      VARCHAR(40)  NOT NULL,                   -- CREATE, UPDATE, VALIDATE, PAYMENT, CANCEL, ...
    entity_type VARCHAR(60)  NOT NULL,                   -- Patient, LabRequest, Invoice, ...
    entity_id   BIGINT,                                  -- id de l'entité concernée (le cas échéant)
    ip_address  VARCHAR(45),                             -- IPv4/IPv6 de la requête
    user_agent  VARCHAR(255),
    details     TEXT,                                    -- résumé optionnel
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_created   ON audit_log (created_at);
CREATE INDEX idx_audit_user      ON audit_log (username, created_at);
CREATE INDEX idx_audit_entity    ON audit_log (entity_type, entity_id);
