-- V16: Catalogue CIM-10 (P2.2). Table de référence des diagnostics codés.
--
-- Le diagnostic des consultations reste en texte libre (colonne `diagnosis`), mais
-- `consultations.icd10_codes` (VARCHAR, codes séparés par virgule — déjà présent depuis V6)
-- est désormais alimenté par auto-complétion depuis ce catalogue. Objectif : fiabiliser
-- l'épidémiologie (top pathologies) et la facturation par acte, sans perdre le texte libre.
--
-- DDL compatible PostgreSQL (prod) ET H2 (dev), comme les autres catalogues (V4).

CREATE TABLE icd10_catalog (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(10)  NOT NULL UNIQUE,
    title      VARCHAR(255) NOT NULL,
    category   VARCHAR(120),
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_icd10_is_active ON icd10_catalog (is_active);

-- ── Amorce : pathologies fréquentes en pratique de clinique africaine ────────
-- Sélection volontairement courte et utile (élargissable via /admin/icd10).
INSERT INTO icd10_catalog (code, title, category) VALUES
    -- Maladies infectieuses et parasitaires
    ('A09',   'Diarrhée et gastro-entérite d''origine présumée infectieuse', 'Maladies infectieuses et parasitaires'),
    ('A90',   'Dengue classique',                                            'Maladies infectieuses et parasitaires'),
    ('B50',   'Paludisme à Plasmodium falciparum',                           'Maladies infectieuses et parasitaires'),
    ('B54',   'Paludisme, sans précision',                                   'Maladies infectieuses et parasitaires'),
    ('B24',   'Maladie due au VIH, sans précision',                          'Maladies infectieuses et parasitaires'),
    ('A15',   'Tuberculose respiratoire confirmée',                          'Maladies infectieuses et parasitaires'),
    ('A01',   'Fièvres typhoïde et paratyphoïde',                            'Maladies infectieuses et parasitaires'),
    ('B82',   'Parasitose intestinale, sans précision',                      'Maladies infectieuses et parasitaires'),
    -- Tumeurs
    ('C50',   'Tumeur maligne du sein',                                      'Tumeurs'),
    ('C53',   'Tumeur maligne du col de l''utérus',                          'Tumeurs'),
    -- Sang et organes hématopoïétiques
    ('D50',   'Anémie par carence en fer',                                   'Maladies du sang'),
    ('D57',   'Drépanocytose',                                               'Maladies du sang'),
    -- Endocriniennes, nutritionnelles et métaboliques
    ('E11',   'Diabète sucré de type 2',                                     'Maladies endocriniennes et métaboliques'),
    ('E10',   'Diabète sucré de type 1',                                     'Maladies endocriniennes et métaboliques'),
    ('E44',   'Malnutrition protéino-énergétique modérée',                   'Maladies endocriniennes et métaboliques'),
    ('E86',   'Hypovolémie (déshydratation)',                               'Maladies endocriniennes et métaboliques'),
    -- Troubles mentaux
    ('F32',   'Épisode dépressif',                                           'Troubles mentaux et du comportement'),
    ('F41',   'Autres troubles anxieux',                                     'Troubles mentaux et du comportement'),
    -- Système nerveux
    ('G40',   'Épilepsie',                                                   'Maladies du système nerveux'),
    ('G43',   'Migraine',                                                    'Maladies du système nerveux'),
    -- Appareil circulatoire
    ('I10',   'Hypertension essentielle (primitive)',                        'Maladies de l''appareil circulatoire'),
    ('I50',   'Insuffisance cardiaque',                                      'Maladies de l''appareil circulatoire'),
    ('I63',   'Infarctus cérébral',                                          'Maladies de l''appareil circulatoire'),
    -- Appareil respiratoire
    ('J00',   'Rhinopharyngite aiguë (rhume banal)',                         'Maladies de l''appareil respiratoire'),
    ('J06.9', 'Infection aiguë des voies respiratoires supérieures, sans précision', 'Maladies de l''appareil respiratoire'),
    ('J18',   'Pneumonie, micro-organisme non précisé',                      'Maladies de l''appareil respiratoire'),
    ('J45',   'Asthme',                                                      'Maladies de l''appareil respiratoire'),
    ('J02',   'Pharyngite aiguë',                                            'Maladies de l''appareil respiratoire'),
    ('J03',   'Amygdalite aiguë',                                            'Maladies de l''appareil respiratoire'),
    -- Appareil digestif
    ('K29',   'Gastrite et duodénite',                                       'Maladies de l''appareil digestif'),
    ('K21',   'Reflux gastro-œsophagien',                                    'Maladies de l''appareil digestif'),
    ('K30',   'Dyspepsie fonctionnelle',                                     'Maladies de l''appareil digestif'),
    ('K35',   'Appendicite aiguë',                                           'Maladies de l''appareil digestif'),
    -- Peau et tissu sous-cutané
    ('L03',   'Cellulite (dermohypodermite)',                               'Maladies de la peau'),
    ('L30',   'Dermatite, sans précision',                                   'Maladies de la peau'),
    -- Système ostéo-articulaire
    ('M54',   'Dorsalgie / lombalgie',                                       'Maladies ostéo-articulaires'),
    ('M25.5', 'Douleur articulaire',                                         'Maladies ostéo-articulaires'),
    -- Appareil génito-urinaire
    ('N39.0', 'Infection des voies urinaires, siège non précisé',           'Maladies de l''appareil génito-urinaire'),
    ('N30',   'Cystite',                                                     'Maladies de l''appareil génito-urinaire'),
    -- Grossesse, accouchement et puerpéralité
    ('O80',   'Accouchement par voie basse spontané',                        'Grossesse, accouchement et puerpéralité'),
    ('O14',   'Pré-éclampsie',                                               'Grossesse, accouchement et puerpéralité'),
    ('Z34',   'Surveillance d''une grossesse normale',                       'Grossesse, accouchement et puerpéralité'),
    -- Symptômes et signes
    ('R50.9', 'Fièvre, sans précision',                                      'Symptômes et signes anormaux'),
    ('R51',   'Céphalée',                                                    'Symptômes et signes anormaux'),
    ('R10',   'Douleur abdominale et pelvienne',                             'Symptômes et signes anormaux'),
    ('R05',   'Toux',                                                        'Symptômes et signes anormaux'),
    ('R11',   'Nausées et vomissements',                                     'Symptômes et signes anormaux'),
    -- Traumatismes
    ('S00',   'Traumatisme superficiel de la tête',                          'Lésions traumatiques et empoisonnements'),
    ('T14',   'Traumatisme de région non précisée du corps',                'Lésions traumatiques et empoisonnements'),
    -- Facteurs influant sur l'état de santé
    ('Z00',   'Examen général sans plainte ni diagnostic signalé',           'Facteurs influant sur l''état de santé');
