-- V18: Webhooks Mobile Money (P3.3). Journal des notifications de paiement reçues des
-- agrégateurs (Orange Money / Wave / MTN MoMo) pour automatiser la confirmation d'encaissement.
-- Sert à la fois de piste d'audit ET de garde-fou d'idempotence : un agrégateur peut rejouer
-- la même notification → la contrainte UNIQUE (provider, transaction_id) empêche le double paiement.
-- DDL compatible PostgreSQL (prod) ET H2 (dev/test), comme les vagues précédentes.

CREATE TABLE payment_webhook_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider        VARCHAR(20)   NOT NULL,            -- ORANGE_MONEY, WAVE, MTN_MOMO
    transaction_id  VARCHAR(100)  NOT NULL,            -- id de transaction de l'agrégateur
    invoice_number  VARCHAR(25),                       -- référence facture transmise (FAC-2026-00001)
    invoice_id      BIGINT        REFERENCES invoices (id),
    amount          NUMERIC(12,2),
    provider_status VARCHAR(30),                       -- statut brut reçu (SUCCESS, FAILED, …)
    status          VARCHAR(20)   NOT NULL DEFAULT 'RECEIVED', -- PROCESSED, REJECTED, DUPLICATE
    error_message   VARCHAR(255),
    received_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_webhook_provider_txn UNIQUE (provider, transaction_id)
);

CREATE INDEX idx_webhook_invoice ON payment_webhook_events (invoice_id);
CREATE INDEX idx_webhook_received_at ON payment_webhook_events (received_at);
