-- V1: Baseline schema — formalizes the existing Auth + Patients tables that were
-- previously generated by Hibernate ddl-auto. From this migration onward the schema
-- is owned by Flyway and validated by Hibernate (ddl-auto=validate).
--
-- DDL is written to be compatible with BOTH PostgreSQL (prod) and H2 (dev):
--   * BIGINT GENERATED BY DEFAULT AS IDENTITY  -> maps to JPA GenerationType.IDENTITY
--   * TIMESTAMP (no time zone)                 -> matches the entities' LocalDateTime
--   * TEXT                                     -> matches @Column(columnDefinition = "TEXT")

CREATE TABLE users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(255) UNIQUE,
    password  VARCHAR(255),
    full_name VARCHAR(255),
    role      VARCHAR(255)
);

CREATE TABLE patients (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_number           VARCHAR(25)  NOT NULL UNIQUE,
    first_name              VARCHAR(60)  NOT NULL,
    last_name               VARCHAR(60)  NOT NULL,
    birth_date              DATE,
    birth_place             VARCHAR(100),
    gender                  VARCHAR(10),
    nationality             VARCHAR(50),
    national_id             VARCHAR(30),
    phone                   VARCHAR(20),
    phone_alt               VARCHAR(20),
    email                   VARCHAR(120),
    address                 TEXT,
    city                    VARCHAR(80),
    emergency_contact_name  VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    blood_type              VARCHAR(5),
    allergies               TEXT,
    chronic_conditions      TEXT,
    medical_history         TEXT,
    assigned_doctor_id      BIGINT,
    insurance_number        VARCHAR(50),
    photo_url               VARCHAR(255),
    notes                   TEXT,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP,
    deleted_at              TIMESTAMP,
    CONSTRAINT fk_patients_assigned_doctor
        FOREIGN KEY (assigned_doctor_id) REFERENCES users (id)
);

CREATE INDEX idx_patients_assigned_doctor ON patients (assigned_doctor_id);
CREATE INDEX idx_patients_deleted_at ON patients (deleted_at);
