-- V20: Multi-tenant à discriminant (P4.2). Une instance héberge plusieurs cliniques.
-- Modèle « shared schema » : une colonne clinic_id sur les tables cliniques cœur, filtrée
-- automatiquement par Hibernate (@TenantId) à partir de l'utilisateur connecté.
-- Compatible PostgreSQL (prod) ET H2 (dev/test).
--
-- NB : les tables cliniques ciblées sont VIDES à cette migration (amorcées par code via
-- DataInitializer, qui s'exécute après Flyway) → ADD COLUMN ... NOT NULL sans défaut est sûr.

-- ── Registre des tenants ───────────────────────────────────────────────────────
CREATE TABLE clinics (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(30)  NOT NULL UNIQUE,
    name       VARCHAR(150) NOT NULL,
    address    TEXT,
    phone      VARCHAR(30),
    email      VARCHAR(120),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Deux cliniques de démonstration (réf. par code dans DataInitializer).
INSERT INTO clinics (code, name, address, phone, email) VALUES
  ('CENTRALE', 'Clinique Centrale', 'Avenue Léopold Sédar Senghor, Dakar', '+221 33 800 00 00', 'contact@clinique-centrale.sn'),
  ('PLATEAU',  'Cabinet du Plateau', 'Rue du Commerce, Abidjan Plateau',   '+225 27 20 00 00', 'contact@cabinet-plateau.ci');

-- ── Appartenance des comptes (NULL = SUPER_ADMIN, transverse) ───────────────────
ALTER TABLE users ADD COLUMN clinic_id BIGINT;
ALTER TABLE users ADD CONSTRAINT fk_users_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id);
CREATE INDEX idx_users_clinic ON users (clinic_id);

-- ── Discriminant @TenantId sur les tables cliniques cœur ────────────────────────
ALTER TABLE patients           ADD COLUMN clinic_id BIGINT NOT NULL;
ALTER TABLE appointments       ADD COLUMN clinic_id BIGINT NOT NULL;
ALTER TABLE consultations      ADD COLUMN clinic_id BIGINT NOT NULL;
ALTER TABLE prescriptions      ADD COLUMN clinic_id BIGINT NOT NULL;
ALTER TABLE prescription_items ADD COLUMN clinic_id BIGINT NOT NULL;
ALTER TABLE invoices           ADD COLUMN clinic_id BIGINT NOT NULL;
ALTER TABLE payments           ADD COLUMN clinic_id BIGINT NOT NULL;
ALTER TABLE lab_requests       ADD COLUMN clinic_id BIGINT NOT NULL;
ALTER TABLE lab_results        ADD COLUMN clinic_id BIGINT NOT NULL;

ALTER TABLE patients           ADD CONSTRAINT fk_patients_clinic           FOREIGN KEY (clinic_id) REFERENCES clinics (id);
ALTER TABLE appointments       ADD CONSTRAINT fk_appointments_clinic       FOREIGN KEY (clinic_id) REFERENCES clinics (id);
ALTER TABLE consultations      ADD CONSTRAINT fk_consultations_clinic      FOREIGN KEY (clinic_id) REFERENCES clinics (id);
ALTER TABLE prescriptions      ADD CONSTRAINT fk_prescriptions_clinic      FOREIGN KEY (clinic_id) REFERENCES clinics (id);
ALTER TABLE prescription_items ADD CONSTRAINT fk_prescription_items_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id);
ALTER TABLE invoices           ADD CONSTRAINT fk_invoices_clinic           FOREIGN KEY (clinic_id) REFERENCES clinics (id);
ALTER TABLE payments           ADD CONSTRAINT fk_payments_clinic           FOREIGN KEY (clinic_id) REFERENCES clinics (id);
ALTER TABLE lab_requests       ADD CONSTRAINT fk_lab_requests_clinic       FOREIGN KEY (clinic_id) REFERENCES clinics (id);
ALTER TABLE lab_results        ADD CONSTRAINT fk_lab_results_clinic        FOREIGN KEY (clinic_id) REFERENCES clinics (id);

CREATE INDEX idx_patients_clinic           ON patients (clinic_id);
CREATE INDEX idx_appointments_clinic       ON appointments (clinic_id);
CREATE INDEX idx_consultations_clinic      ON consultations (clinic_id);
CREATE INDEX idx_prescriptions_clinic      ON prescriptions (clinic_id);
CREATE INDEX idx_prescription_items_clinic ON prescription_items (clinic_id);
CREATE INDEX idx_invoices_clinic           ON invoices (clinic_id);
CREATE INDEX idx_payments_clinic           ON payments (clinic_id);
CREATE INDEX idx_lab_requests_clinic       ON lab_requests (clinic_id);
CREATE INDEX idx_lab_results_clinic        ON lab_results (clinic_id);
