-- V21: Refresh tokens + révocation JWT (P4.4).
-- Avant : un seul access token JWT de 24h, stateless, NON révocable.
-- Après : access token court (15 min) + refresh token long (7j) stocké côté serveur
--         (donc révocable + rotation), et une « version de token » par utilisateur qui
--         invalide instantanément TOUS les access tokens en cours quand on l'incrémente.
-- Compatible PostgreSQL (prod) ET H2 (dev/test).

-- ── Version de token : claim « tv » embarqué dans chaque access token ───────────
-- JwtFilter compare le « tv » du token à users.token_version ; un écart => token rejeté.
-- Incrémentée lors d'un logout-all / désactivation / suppression / réutilisation
-- détectée d'un refresh token volé => révocation IMMÉDIATE de tous les access tokens.
ALTER TABLE users ADD COLUMN token_version INT NOT NULL DEFAULT 0;

-- ── Refresh tokens (opaques, stockés en HACHÉ) ─────────────────────────────────
-- On ne stocke JAMAIS la valeur brute : seulement son SHA-256 (hex). Le client garde
-- le brut ; une fuite de la base ne donne pas de refresh token utilisable.
-- NB : pas de @TenantId ici (comme users) — l'auth est globale et keyée par user_id,
-- qui résout la clinique. Le endpoint /refresh tourne sans contexte tenant.
CREATE TABLE refresh_tokens (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    token_hash     VARCHAR(64)  NOT NULL UNIQUE,
    expires_at     TIMESTAMP    NOT NULL,
    revoked_at     TIMESTAMP,
    replaced_by_id BIGINT,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
