-- V34 (Tier E1) : certificats médicaux (arrêt de travail, repos, aptitude, présence…).
-- @TenantId clinic_id (cloisonné par clinique) ; certificate_number UNIQUE GLOBAL (numérotation
-- native non-tenant comme les ordonnances). Le corps est saisi par le médecin (pas de diagnostic
-- injecté → confidentialité). Compatible PostgreSQL (prod) ET H2 (dev/test).
CREATE TABLE medical_certificates (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id          BIGINT,
    certificate_number VARCHAR(25)  NOT NULL UNIQUE,
    type               VARCHAR(30)  NOT NULL,
    patient_id         BIGINT       NOT NULL REFERENCES patients (id),
    doctor_id          BIGINT       NOT NULL REFERENCES users (id),
    consultation_id    BIGINT       REFERENCES consultations (id),
    issue_date         DATE         NOT NULL,
    rest_start_date    DATE,
    rest_end_date      DATE,
    rest_days          INTEGER,
    content            TEXT,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_certificates_patient ON medical_certificates (patient_id);
CREATE INDEX idx_certificates_clinic  ON medical_certificates (clinic_id);
