-- V36 (Tier E2-B) : catalogue des interactions médicamenteuses.
-- Table de référence GLOBALE (savoir universel, comme icd10_catalog en V16) — pas de clinic_id.
-- Sert au recoupement NON-BLOQUANT à la dispensation (par paire de DCI). Amorce volontairement
-- courte de paires bien connues ; élargissable par curation. Compatible PostgreSQL ET H2.
CREATE TABLE drug_interactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dci_a       VARCHAR(150) NOT NULL,
    dci_b       VARCHAR(150) NOT NULL,
    severity    VARCHAR(20)  NOT NULL DEFAULT 'MODEREE',   -- MINEURE / MODEREE / MAJEURE
    description VARCHAR(500),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_drug_interactions_active ON drug_interactions (is_active);

-- ── Amorce : interactions fréquentes / cliniquement importantes ──────────────
INSERT INTO drug_interactions (dci_a, dci_b, severity, description) VALUES
    ('Warfarine',    'Aspirine',        'MAJEURE', 'Risque hémorragique majoré (potentialisation de l''anticoagulation).'),
    ('Warfarine',    'Ibuprofène',      'MAJEURE', 'AINS + anticoagulant : risque hémorragique digestif accru.'),
    ('Tramadol',     'Fluoxétine',      'MAJEURE', 'Risque de syndrome sérotoninergique.'),
    ('Simvastatine', 'Clarithromycine', 'MAJEURE', 'Risque de rhabdomyolyse (inhibition du métabolisme de la statine).'),
    ('Méthotrexate', 'Amoxicilline',    'MODEREE', 'Diminution de l''élimination du méthotrexate : toxicité accrue.'),
    ('Ibuprofène',   'Énalapril',       'MODEREE', 'AINS + IEC : insuffisance rénale et baisse de l''effet antihypertenseur.'),
    ('Aspirine',     'Ibuprofène',      'MODEREE', 'Association de deux AINS : risque digestif accru, effet antiagrégant réduit.'),
    ('Digoxine',     'Furosémide',      'MODEREE', 'Hypokaliémie induite par le diurétique majorant la toxicité de la digoxine.');
