-- V37 (Tier E3) : MFA/2FA par TOTP (opt-in, chaîne web session).
-- mfa_secret = clé TOTP base32, CHIFFRÉE au repos (PhiStringConverter, comme les PHI).
-- Codes de secours = hachés (BCrypt) dans une table dédiée, à usage unique.
-- Compatible PostgreSQL (prod) ET H2 (dev/test).
ALTER TABLE users ADD COLUMN mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN mfa_secret  VARCHAR(255);

CREATE TABLE mfa_recovery_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    code_hash  VARCHAR(100) NOT NULL,
    used_at    TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_mfa_recovery_user ON mfa_recovery_codes (user_id);
