-- V38 (Phase 3 desktop) : licence + mode d'essai.
-- Table INSTALLATION-GLOBALE (pas de clinic_id / @TenantId) : la licence gouverne
-- tout le poste, pas une clinique en particulier. Une seule ligne en pratique,
-- gérée par LicenseService (charge la 1re ligne, ou la crée au 1er démarrage).
-- La clé de licence est un jeton signé Ed25519 vérifié HORS-LIGNE (aucun serveur).
-- Compatible PostgreSQL (prod/desktop) ET H2 (dev/test).
CREATE TABLE license_activation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_token    TEXT,                 -- jeton signé activé (NULL = pas encore de licence → essai)
    edition          VARCHAR(30),          -- reflet du contenu de la licence (affichage)
    clinic_name      VARCHAR(200),
    expires_on       DATE,                 -- date d'expiration de la licence activée
    activated_at     TIMESTAMP,            -- horodatage de la dernière activation
    trial_started_at TIMESTAMP,            -- début de l'essai (source « base »)
    last_seen_at     TIMESTAMP,            -- dernière heure vue par l'app (détection recul d'horloge)
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
