-- V3: Departments — small reference module (organizational services/specialties).
-- Pulled up in the build order because users/appointments/consultations/hospitalizations
-- will FK to this table. Soft-disable is modelled with is_active (no deleted_at column).
--
-- DDL kept compatible with BOTH PostgreSQL (prod) and H2 (dev), matching V1's conventions.

CREATE TABLE departments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,   -- MED_GEN, MATERNITE, DENTAIRE…
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    color       VARCHAR(7),                     -- hex pour l'UI (#2563eb)
    is_active   BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_departments_is_active ON departments (is_active);

-- Seed: reference data needed in every environment (dev + prod), so it lives in the
-- migration rather than DataInitializer.
INSERT INTO departments (code, name, description, color) VALUES
    ('MED_GEN',   'Médecine générale',  'Consultations de médecine générale',        '#2563eb'),
    ('PEDIATRIE', 'Pédiatrie',          'Suivi et soins des enfants',                '#0ea5e9'),
    ('MATERNITE', 'Maternité',          'Suivi de grossesse et accouchements',       '#ec4899'),
    ('GYNECO',    'Gynécologie',        'Gynécologie (hors maternité)',              '#d946ef'),
    ('DENTAIRE',  'Dentisterie',        'Soins dentaires',                           '#f59e0b'),
    ('OPHTALMO',  'Ophtalmologie',      'Soins et examens de la vue',                '#14b8a6'),
    ('LABO',      'Laboratoire',        'Analyses biologiques',                      '#22c55e'),
    ('RADIO',     'Radiologie',         'Imagerie médicale',                         '#64748b'),
    ('PHARMACIE', 'Pharmacie',          'Dispensation des médicaments',              '#16a34a'),
    ('URGENCES',  'Urgences',           'Accueil et soins d''urgence',               '#ef4444');
