-- V4: Config & Catalogs (module 3 — "socle"). Four reference tables that downstream
-- modules depend on:
--   * clinic_config       — singleton row holding clinic identity + feature flags
--   * insurance_providers — mutuelles/assurances partenaires (patients/invoices FK here)
--   * act_catalog         — billable acts with default prices (invoice_items FK here)
--   * lab_test_catalog    — analyses with prices (lab_requests FK here)
--
-- DDL kept compatible with BOTH PostgreSQL (prod) and H2 (dev), matching V1/V3 conventions.

-- ── clinic_config ──────────────────────────────────────────────────────────
-- One row per instance. Seeded immediately so the app always has a config to read.
CREATE TABLE clinic_config (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(150) NOT NULL,
    slogan                 VARCHAR(255),
    address                TEXT,
    phone                  VARCHAR(30),
    email                  VARCHAR(120),
    website                VARCHAR(255),
    logo_url               VARCHAR(255),
    currency               VARCHAR(10)  NOT NULL DEFAULT 'XOF',
    timezone               VARCHAR(50)  NOT NULL DEFAULT 'Africa/Dakar',
    default_language       VARCHAR(10)  NOT NULL DEFAULT 'fr',
    -- Modules activés (feature flags)
    module_pharmacy        BOOLEAN NOT NULL DEFAULT TRUE,
    module_lab             BOOLEAN NOT NULL DEFAULT TRUE,
    module_maternity       BOOLEAN NOT NULL DEFAULT FALSE,
    module_dental          BOOLEAN NOT NULL DEFAULT FALSE,
    module_radiology       BOOLEAN NOT NULL DEFAULT FALSE,
    module_hospitalization BOOLEAN NOT NULL DEFAULT FALSE,
    -- Paiements
    mobile_money_enabled   BOOLEAN NOT NULL DEFAULT FALSE,
    mobile_money_provider  VARCHAR(30),
    insurance_enabled      BOOLEAN NOT NULL DEFAULT FALSE,
    -- Numérotation
    patient_record_prefix  VARCHAR(10) NOT NULL DEFAULT 'PAT',
    invoice_prefix         VARCHAR(10) NOT NULL DEFAULT 'FAC',
    prescription_prefix    VARCHAR(10) NOT NULL DEFAULT 'ORD',
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP
);

INSERT INTO clinic_config (name, slogan, currency, timezone) VALUES
    ('ClinicApp', 'Gestion de clinique moderne', 'XOF', 'Africa/Dakar');

-- ── insurance_providers ────────────────────────────────────────────────────
CREATE TABLE insurance_providers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(150) NOT NULL,
    code             VARCHAR(30) UNIQUE,
    type             VARCHAR(30),                 -- PUBLIQUE, PRIVEE, MUTUELLE
    coverage_percent NUMERIC(5,2),                -- % pris en charge par défaut
    contact          VARCHAR(255),
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_insurance_is_active ON insurance_providers (is_active);

INSERT INTO insurance_providers (name, code, type, coverage_percent, contact) VALUES
    ('IPM (Institution de Prévoyance Maladie)', 'IPM',  'PUBLIQUE', 80.00, NULL),
    ('Mutuelle de Santé',                        'MUT',  'MUTUELLE', 70.00, NULL),
    ('NSIA Assurances',                          'NSIA', 'PRIVEE',   75.00, NULL),
    ('Payant comptant (aucune assurance)',       'CASH', 'PRIVEE',    0.00, NULL);

-- ── act_catalog ────────────────────────────────────────────────────────────
CREATE TABLE act_catalog (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(30)  NOT NULL UNIQUE,
    name          VARCHAR(150) NOT NULL,
    department_id BIGINT REFERENCES departments (id),
    price         NUMERIC(12,2) NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_act_catalog_department ON act_catalog (department_id);
CREATE INDEX idx_act_catalog_is_active  ON act_catalog (is_active);

INSERT INTO act_catalog (code, name, department_id, price) VALUES
    ('CONS_GEN',  'Consultation médecine générale', (SELECT id FROM departments WHERE code = 'MED_GEN'),   5000.00),
    ('CONS_SPEC', 'Consultation spécialiste',       NULL,                                                10000.00),
    ('CONS_PED',  'Consultation pédiatrique',       (SELECT id FROM departments WHERE code = 'PEDIATRIE'), 6000.00),
    ('SOIN_INF',  'Soins infirmiers',               NULL,                                                 2000.00),
    ('PANSEMENT', 'Pansement',                       NULL,                                                 1500.00),
    ('INJECTION', 'Injection',                       NULL,                                                 1000.00);

-- ── lab_test_catalog ───────────────────────────────────────────────────────
CREATE TABLE lab_test_catalog (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(30)  NOT NULL UNIQUE,
    name             VARCHAR(150) NOT NULL,
    category         VARCHAR(50),                 -- HEMATOLOGIE, BIOCHIMIE, SEROLOGIE…
    price            NUMERIC(12,2) NOT NULL,
    turnaround_hours INT,
    reference_range  TEXT,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_lab_catalog_is_active ON lab_test_catalog (is_active);

INSERT INTO lab_test_catalog (code, name, category, price, turnaround_hours, reference_range) VALUES
    ('NFS',      'Numération Formule Sanguine', 'HEMATOLOGIE', 4000.00, 24, NULL),
    ('GLYCEMIE', 'Glycémie à jeun',             'BIOCHIMIE',   2000.00,  2, '0.70 - 1.10 g/L'),
    ('CREAT',    'Créatininémie',               'BIOCHIMIE',   2500.00,  4, '6 - 12 mg/L'),
    ('HIV',      'Sérologie VIH',               'SEROLOGIE',   3000.00, 24, 'Négatif'),
    ('TDR_PALU', 'Test de diagnostic rapide paludisme', 'BACTERIO', 1500.00, 1, 'Négatif');
