-- V5: Appointments (module 03 — agenda). The appointments table deferred from the
-- baseline now lands here, once patients/users/departments exist as FK targets.
-- DDL kept compatible with BOTH PostgreSQL (prod) and H2 (dev), matching V1/V3/V4.

CREATE TABLE appointments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id    BIGINT NOT NULL REFERENCES patients (id),
    doctor_id     BIGINT NOT NULL REFERENCES users (id),
    department_id BIGINT REFERENCES departments (id),
    start_time    TIMESTAMP NOT NULL,
    end_time      TIMESTAMP NOT NULL,
    status        VARCHAR(20) NOT NULL DEFAULT 'PLANIFIE',
                  -- PLANIFIE, CONFIRME, EN_COURS, TERMINE, ANNULE, ABSENT
    type          VARCHAR(30),  -- CONSULTATION, SUIVI, URGENCE, TELECONSULTATION
    reason        TEXT,
    notes         TEXT,
    reminder_sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_by    BIGINT REFERENCES users (id),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,
    cancelled_at  TIMESTAMP,
    cancel_reason TEXT
);

CREATE INDEX idx_appointments_patient ON appointments (patient_id);
CREATE INDEX idx_appointments_doctor  ON appointments (doctor_id);
CREATE INDEX idx_appointments_date    ON appointments (start_time);
CREATE INDEX idx_appointments_status  ON appointments (status);
