-- V6: Consultations & Ordonnances (module 04 — clinical pivot). Consultations hang
-- off appointments + patients + doctors; prescriptions + their items hang off
-- consultations. DDL kept compatible with BOTH PostgreSQL (prod) and H2 (dev),
-- matching V1..V5.
--
-- NB (deviation from docs/DATABASE.md): `diagnosis` is NULLABLE here, not NOT NULL.
-- The business rule (module 04 spec) is "le diagnostic est obligatoire pour CLÔTURER"
-- — a consultation may stay EN_COURS with an empty diagnosis and is filled in
-- progressively. The non-blank-diagnosis rule is enforced in ConsultationService
-- on the EN_COURS → TERMINE transition.

CREATE TABLE consultations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id    BIGINT REFERENCES appointments (id),
    patient_id        BIGINT NOT NULL REFERENCES patients (id),
    doctor_id         BIGINT NOT NULL REFERENCES users (id),
    department_id     BIGINT REFERENCES departments (id),
    consultation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Constantes vitales
    weight_kg         NUMERIC(5,2),
    height_cm         NUMERIC(5,1),
    temperature_c     NUMERIC(4,1),
    bp_systolic       INT,
    bp_diastolic      INT,
    pulse_bpm         INT,
    spo2_percent      NUMERIC(4,1),
    respiratory_rate  INT,
    -- Clinique
    chief_complaint   TEXT,
    history           TEXT,
    physical_exam     TEXT,
    diagnosis         TEXT,
    icd10_codes       VARCHAR(255),
    treatment_plan    TEXT,
    follow_up_date    DATE,
    is_emergency      BOOLEAN NOT NULL DEFAULT FALSE,
    status            VARCHAR(20) NOT NULL DEFAULT 'EN_COURS',
                      -- EN_COURS, TERMINE, ANNULE
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP
);
CREATE INDEX idx_consultations_patient ON consultations (patient_id);
CREATE INDEX idx_consultations_doctor  ON consultations (doctor_id);
CREATE INDEX idx_consultations_date    ON consultations (consultation_date);

CREATE TABLE prescriptions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_number VARCHAR(25) NOT NULL UNIQUE,  -- ORD-2026-00001
    consultation_id     BIGINT REFERENCES consultations (id),
    patient_id          BIGINT NOT NULL REFERENCES patients (id),
    doctor_id           BIGINT NOT NULL REFERENCES users (id),
    issue_date          DATE NOT NULL DEFAULT CURRENT_DATE,
    validity_days       INT NOT NULL DEFAULT 30,
    notes               TEXT,
    is_dispensed        BOOLEAN NOT NULL DEFAULT FALSE,
    dispensed_at        TIMESTAMP,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_prescriptions_consultation ON prescriptions (consultation_id);
CREATE INDEX idx_prescriptions_patient      ON prescriptions (patient_id);

CREATE TABLE prescription_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id BIGINT NOT NULL REFERENCES prescriptions (id) ON DELETE CASCADE,
    drug_id         BIGINT,                  -- FK→drugs(id) added with the Pharmacy module
    drug_name       VARCHAR(150) NOT NULL,   -- saisie libre si hors stock
    dosage          VARCHAR(100) NOT NULL,   -- ex: "500mg"
    frequency       VARCHAR(100) NOT NULL,   -- ex: "3x/jour"
    duration        VARCHAR(100),            -- ex: "7 jours"
    quantity        INT,
    instructions    TEXT,
    sort_order      INT NOT NULL DEFAULT 0
);
CREATE INDEX idx_prescription_items_prescription ON prescription_items (prescription_id);
