-- V7: Pharmacie & Stock (module 05 — Wave 2). Drugs catalogue + physical stock batches
-- + dispensations (stock-out, optionally against a prescription) and their lines.
-- DDL kept compatible with BOTH PostgreSQL (prod) and H2 (dev), matching V1..V6.

CREATE TABLE drugs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                  VARCHAR(30) UNIQUE,        -- code interne ou DCI
    name                  VARCHAR(150) NOT NULL,     -- nom commercial
    generic_name          VARCHAR(150),              -- DCI
    category              VARCHAR(50),               -- ANTIBIOTIQUE, ANALGESIQUE…
    form                  VARCHAR(30),               -- COMPRIME, SIROP, INJECTABLE…
    dosage_strength       VARCHAR(50),               -- ex: 500mg, 250mg/5ml
    unit                  VARCHAR(20) NOT NULL,      -- COMPRIME, ML, FLACON…
    requires_prescription BOOLEAN NOT NULL DEFAULT TRUE,
    is_active             BOOLEAN NOT NULL DEFAULT TRUE,
    notes                 TEXT,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_drugs_name ON drugs (name);

CREATE TABLE stock_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_id         BIGINT NOT NULL REFERENCES drugs (id),
    batch_number    VARCHAR(50),
    expiry_date     DATE NOT NULL,
    quantity        INT NOT NULL DEFAULT 0,
    quantity_alert  INT NOT NULL DEFAULT 10,         -- seuil d'alerte de rupture
    purchase_price  NUMERIC(12,2),
    selling_price   NUMERIC(12,2) NOT NULL,
    supplier        VARCHAR(150),
    received_at     DATE NOT NULL DEFAULT CURRENT_DATE,
    received_by     BIGINT REFERENCES users (id),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP
);
CREATE INDEX idx_stock_drug   ON stock_items (drug_id);
CREATE INDEX idx_stock_expiry ON stock_items (expiry_date);

CREATE TABLE dispensations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id  BIGINT REFERENCES prescriptions (id),  -- null = vente libre
    patient_id       BIGINT NOT NULL REFERENCES patients (id),
    pharmacist_id    BIGINT NOT NULL REFERENCES users (id),
    dispensed_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount     NUMERIC(12,2) NOT NULL DEFAULT 0,
    notes            TEXT
);
CREATE INDEX idx_dispensations_patient ON dispensations (patient_id);
CREATE INDEX idx_dispensations_date    ON dispensations (dispensed_at);

CREATE TABLE dispensation_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispensation_id BIGINT NOT NULL REFERENCES dispensations (id) ON DELETE CASCADE,
    stock_item_id   BIGINT NOT NULL REFERENCES stock_items (id),
    quantity        INT NOT NULL,
    unit_price      NUMERIC(12,2) NOT NULL,
    total_price     NUMERIC(12,2) NOT NULL
);
CREATE INDEX idx_dispensation_items_dispensation ON dispensation_items (dispensation_id);

-- Formalize the FK left dangling in V6: prescription_items.drug_id → drugs(id)
-- (drugs did not exist yet when V6 ran). The column already holds catalogue ids.
ALTER TABLE prescription_items
    ADD CONSTRAINT fk_prescription_items_drug
    FOREIGN KEY (drug_id) REFERENCES drugs (id);
