-- V8: Laboratoire (module 8). Lab orders raised from consultations, the analyses they
-- carry, and the results entered by laborantins / validated by clinicians.
--   * lab_requests       — the order header (patient, prescriber, priority, status)
--   * lab_request_items  — one line per analysis, FK→lab_test_catalog (seeded in V4)
--   * lab_results        — the measured value for an item, abnormality flag + validation
--
-- lab_test_catalog already exists (V4). DDL kept compatible with PostgreSQL + H2.

-- ── lab_requests ─────────────────────────────────────────────────────────────
CREATE TABLE lab_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number  VARCHAR(25)  NOT NULL UNIQUE,
    consultation_id BIGINT REFERENCES consultations (id),
    patient_id      BIGINT NOT NULL REFERENCES patients (id),
    doctor_id       BIGINT NOT NULL REFERENCES users (id),
    requested_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    priority        VARCHAR(10) NOT NULL DEFAULT 'NORMAL',   -- NORMAL, URGENT
    status          VARCHAR(20) NOT NULL DEFAULT 'EN_ATTENTE', -- EN_ATTENTE, EN_COURS, VALIDE, LIVRE
    notes           TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_lab_requests_patient ON lab_requests (patient_id);
CREATE INDEX idx_lab_requests_doctor  ON lab_requests (doctor_id);
CREATE INDEX idx_lab_requests_status  ON lab_requests (status);

-- ── lab_request_items ────────────────────────────────────────────────────────
CREATE TABLE lab_request_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_request_id BIGINT NOT NULL REFERENCES lab_requests (id) ON DELETE CASCADE,
    test_id        BIGINT NOT NULL REFERENCES lab_test_catalog (id),
    status         VARCHAR(20) NOT NULL DEFAULT 'EN_ATTENTE'  -- EN_ATTENTE, SAISI
);

CREATE INDEX idx_lab_request_items_request ON lab_request_items (lab_request_id);

-- ── lab_results ──────────────────────────────────────────────────────────────
CREATE TABLE lab_results (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_request_item_id BIGINT NOT NULL UNIQUE REFERENCES lab_request_items (id),
    laborantin_id       BIGINT REFERENCES users (id),
    result_value        TEXT NOT NULL,
    unit                VARCHAR(30),
    reference_range     TEXT,
    is_abnormal         BOOLEAN NOT NULL DEFAULT FALSE,
    validated_at        TIMESTAMP,
    validated_by        BIGINT REFERENCES users (id),
    notes               TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_lab_results_item ON lab_results (lab_request_item_id);
