-- V9: Imagerie médicale (module 9). Imaging orders raised from consultations, the report
-- written by the radiologist, and the images attached. Mirrors the Lab module's
-- request → result shape, but the "result" is a narrative report (findings + conclusion)
-- plus images for the whole request rather than numeric values per item.
--   * radiology_exam_catalog  — seeded reference of exams (radio, écho, scanner, IRM, mammo)
--   * radiology_requests      — the order header (patient, prescriber, priority, status)
--   * radiology_request_items — one line per exam ordered, FK→radiology_exam_catalog
--   * radiology_reports       — the radiologist's compte-rendu, 1:1 with a request
--   * radiology_images        — image files attached to a request (served under /uploads/**)
--
-- DDL kept compatible with BOTH PostgreSQL (prod) and H2 (dev), matching prior migrations.

-- ── radiology_exam_catalog ────────────────────────────────────────────────────
CREATE TABLE radiology_exam_catalog (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(30)  NOT NULL UNIQUE,
    name       VARCHAR(150) NOT NULL,
    type       VARCHAR(30),   -- RADIOGRAPHIE, ECHOGRAPHIE, SCANNER, IRM, MAMMOGRAPHIE
    region     VARCHAR(100),
    price      NUMERIC(12,2) NOT NULL,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_radiology_catalog_is_active ON radiology_exam_catalog (is_active);

INSERT INTO radiology_exam_catalog (code, name, type, region, price) VALUES
    ('RX_THORAX',  'Radiographie du thorax',       'RADIOGRAPHIE', 'Thorax',   8000.00),
    ('RX_ASP',     'Radiographie ASP (abdomen)',   'RADIOGRAPHIE', 'Abdomen',  8000.00),
    ('RX_MEMBRE',  'Radiographie d''un membre',    'RADIOGRAPHIE', 'Membre',   7000.00),
    ('ECHO_ABDO',  'Échographie abdominale',       'ECHOGRAPHIE',  'Abdomen', 15000.00),
    ('ECHO_OBST',  'Échographie obstétricale',     'ECHOGRAPHIE',  'Pelvis',  15000.00),
    ('SCAN_CRANE', 'Scanner cérébral',             'SCANNER',      'Crâne',   50000.00),
    ('IRM_RACHIS', 'IRM du rachis lombaire',       'IRM',          'Rachis',  90000.00),
    ('MAMMO',      'Mammographie bilatérale',      'MAMMOGRAPHIE', 'Sein',    20000.00);

-- ── radiology_requests ─────────────────────────────────────────────────────────
CREATE TABLE radiology_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number  VARCHAR(25)  NOT NULL UNIQUE,
    consultation_id BIGINT REFERENCES consultations (id),
    patient_id      BIGINT NOT NULL REFERENCES patients (id),
    doctor_id       BIGINT NOT NULL REFERENCES users (id),
    requested_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    priority        VARCHAR(10) NOT NULL DEFAULT 'NORMAL',     -- NORMAL, URGENT
    status          VARCHAR(20) NOT NULL DEFAULT 'EN_ATTENTE', -- EN_ATTENTE, EN_COURS, VALIDE, LIVRE, ANNULE
    clinical_info   TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_radiology_requests_patient ON radiology_requests (patient_id);
CREATE INDEX idx_radiology_requests_doctor  ON radiology_requests (doctor_id);
CREATE INDEX idx_radiology_requests_status  ON radiology_requests (status);

-- ── radiology_request_items ──────────────────────────────────────────────────────
CREATE TABLE radiology_request_items (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radiology_request_id BIGINT NOT NULL REFERENCES radiology_requests (id) ON DELETE CASCADE,
    exam_id              BIGINT NOT NULL REFERENCES radiology_exam_catalog (id)
);

CREATE INDEX idx_radiology_request_items_request ON radiology_request_items (radiology_request_id);

-- ── radiology_reports ──────────────────────────────────────────────────────────────
CREATE TABLE radiology_reports (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radiology_request_id BIGINT NOT NULL UNIQUE REFERENCES radiology_requests (id),
    radiologist_id       BIGINT REFERENCES users (id),
    findings             TEXT,
    conclusion           TEXT,
    validated_at         TIMESTAMP,
    validated_by         BIGINT REFERENCES users (id),
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_radiology_reports_request ON radiology_reports (radiology_request_id);

-- ── radiology_images ─────────────────────────────────────────────────────────────────
CREATE TABLE radiology_images (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radiology_request_id BIGINT NOT NULL REFERENCES radiology_requests (id) ON DELETE CASCADE,
    file_path            VARCHAR(255) NOT NULL,
    caption              VARCHAR(255),
    uploaded_by          BIGINT REFERENCES users (id),
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_radiology_images_request ON radiology_images (radiology_request_id);
